apiVersion: v1
kind: Service
metadata:
  name: app1-svc
  namespace: apps
  annotations:
    harness.io/managed: true
spec:
  type: ClusterIP
  selector:
    app: app1
  ports:
    - port: 8080
      name: http
      targetPort: 8080