harnessApiVersion: '1.0'
type: INFRA_DEFINITION
cloudProviderType: KUBERNETES_CLUSTER
deploymentType: KUBERNETES
infrastructure:
- type: DIRECT_KUBERNETES
  cloudProviderName: Kubernetes Cluster
  namespace: prod
  releaseName: release-${infra.kubernetes.infraId}
